#!/usr/bin/env bash
set -eo pipefail

declare -A grammars=(
    ['ada']=' -url https://github.com/briot/tree-sitter-ada'
    ['agda']=' -url https://github.com/tree-sitter/tree-sitter-agda'
    ['angular']=' -url https://github.com/dlvandenberg/tree-sitter-angular'
    ['apex']=' -url https://github.com/aheber/tree-sitter-sfapex -src apex/src'
    ['arduino']=' -url https://github.com/ObserverOfTime/tree-sitter-arduino'
    ['asm']=' -url https://github.com/RubixDev/tree-sitter-asm'
    ['astro']=' -url https://github.com/virchau13/tree-sitter-astro'
    ['authzed']=' -url https://github.com/mleonidas/tree-sitter-authzed'
    ['awk']=' -url https://github.com/Beaglefoot/tree-sitter-awk'
    ['bash']=' -url https://github.com/tree-sitter/tree-sitter-bash'
    ['bass']=' -url https://github.com/vito/tree-sitter-bass'
    ['beancount']=' -url https://github.com/polarmutex/tree-sitter-beancount'
    ['bibtex']=' -url https://github.com/latex-lsp/tree-sitter-bibtex'
    ['bicep']=' -url https://github.com/amaanq/tree-sitter-bicep'
    ['bitbake']=' -url https://github.com/amaanq/tree-sitter-bitbake'
    ['blueprint']=' -url https://gitlab.com/gabmus/tree-sitter-blueprint.git'
    ['bp']=' -url https://github.com/ambroisie/tree-sitter-bp'
    ['c']=' -url https://github.com/tree-sitter/tree-sitter-c'
    ['c-sharp']=' -url https://github.com/tree-sitter/tree-sitter-c-sharp'
    ['cairo']=' -url https://github.com/amaanq/tree-sitter-cairo'
    ['capnp']=' -url https://github.com/amaanq/tree-sitter-capnp'
    ['chatito']=' -url https://github.com/ObserverOfTime/tree-sitter-chatito'
    ['clojure']=' -url https://github.com/sogaiu/tree-sitter-clojure'
    ['cmake']=' -url https://github.com/uyha/tree-sitter-cmake'
    ['comment']=' -url https://github.com/stsewd/tree-sitter-comment'
    ['commonlisp']=' -url https://github.com/theHamsta/tree-sitter-commonlisp'
    ['cooklang']=' -url https://github.com/addcninblue/tree-sitter-cooklang'
    ['corn']=' -url https://github.com/jakestanger/tree-sitter-corn'
    ['cpon']=' -url https://github.com/amaanq/tree-sitter-cpon'
    ['cpp']=' -url https://github.com/tree-sitter/tree-sitter-cpp'
    ['css']=' -url https://github.com/tree-sitter/tree-sitter-css'
    ['csv']=' -url https://github.com/amaanq/tree-sitter-csv -src csv/src'
    ['cuda']=' -url https://github.com/theHamsta/tree-sitter-cuda'
    ['cue']=' -url https://github.com/eonpatapon/tree-sitter-cue'
    ['cylc']=' -url https://github.com/elliotfontaine/tree-sitter-cylc'
    ['d']=' -url https://github.com/gdamore/tree-sitter-d'
    ['dart']=' -url https://github.com/UserNobody14/tree-sitter-dart'
    ['desktop']=' -url https://github.com/ValdezFOmar/tree-sitter-desktop'
    ['devicetree']=' -url https://github.com/joelspadin/tree-sitter-devicetree'
    ['dhall']=' -url https://github.com/jbellerb/tree-sitter-dhall'
    ['diff']=' -url https://github.com/the-mikedavis/tree-sitter-diff'
    ['disassembly']=' -url https://github.com/ColinKennedy/tree-sitter-disassembly'
    ['djot']=' -url https://github.com/treeman/tree-sitter-djot'
    ['dockerfile']=' -url https://github.com/camdencheek/tree-sitter-dockerfile'
    ['dot']=' -url https://github.com/rydesun/tree-sitter-dot'
    ['doxygen']=' -url https://github.com/amaanq/tree-sitter-doxygen'
    ['dtd']=' -url https://github.com/tree-sitter-grammars/tree-sitter-xml -src dtd/src'
    ['earthfile']=' -url https://github.com/glehmann/tree-sitter-earthfile'
    ['ebnf']=' -url https://github.com/RubixDev/ebnf -src crates/tree-sitter-ebnf/src'
    ['editorconfig']=' -url https://github.com/ValdezFOmar/tree-sitter-editorconfig'
    ['eds']=' -url https://github.com/uyha/tree-sitter-eds'
    ['eex']=' -url https://github.com/connorlay/tree-sitter-eex'
    ['elisp']=' -url https://github.com/Wilfred/tree-sitter-elisp'
    ['elixir']=' -url https://github.com/elixir-lang/tree-sitter-elixir'
    ['elm']=' -url https://github.com/elm-tooling/tree-sitter-elm'
    ['elsa']=' -url https://github.com/glapa-grossklag/tree-sitter-elsa'
    ['elvish']=' -url https://github.com/elves/tree-sitter-elvish'
    ['embedded-template']=' -url https://github.com/tree-sitter/tree-sitter-embedded-template'
    ['erlang']=' -url https://github.com/WhatsApp/tree-sitter-erlang'
    ['facility']=' -url https://github.com/FacilityApi/tree-sitter-facility'
    ['faust']=' -url https://github.com/khiner/tree-sitter-faust'
    ['fennel']=' -url https://github.com/alexmozaidze/tree-sitter-fennel'
    ['fidl']=' -url https://github.com/google/tree-sitter-fidl'
    ['firrtl']=' -url https://github.com/amaanq/tree-sitter-firrtl'
    ['fish']=' -url https://github.com/ram02z/tree-sitter-fish'
    ['foam']=' -url https://github.com/FoamScience/tree-sitter-foam'
    ['forth']=' -url https://github.com/AlexanderBrevig/tree-sitter-forth'
    ['fortran']=' -url https://github.com/stadelmanma/tree-sitter-fortran'
    ['fsh']=' -url https://github.com/mgramigna/tree-sitter-fsh'
    ['fsharp']=' -url https://github.com/ionide/tree-sitter-fsharp -src fsharp/src'
    ['fsharp-signature']=' -url https://github.com/ionide/tree-sitter-fsharp -src fsharp_signature/src'
    ['func']=' -url https://github.com/amaanq/tree-sitter-func'
    ['fusion']=' -url https://gitlab.com/jirgn/tree-sitter-fusion.git'
    ['gap']=' -url https://github.com/gap-system/tree-sitter-gap'
    ['gaptst']=' -url https://github.com/gap-system/tree-sitter-gaptst'
    ['gdscript']=' -url https://github.com/PrestonKnopp/tree-sitter-gdscript'
    ['gdshader']=' -url https://github.com/GodOfAvacyn/tree-sitter-gdshader'
    ['git-config']=' -url https://github.com/the-mikedavis/tree-sitter-git-config'
    ['git-rebase']=' -url https://github.com/the-mikedavis/tree-sitter-git-rebase'
    ['gitattributes']=' -url https://github.com/ObserverOfTime/tree-sitter-gitattributes'
    ['gitcommit']=' -url https://github.com/gbprod/tree-sitter-gitcommit'
    ['gitignore']=' -url https://github.com/shunsambongi/tree-sitter-gitignore'
    ['gleam']=' -url https://github.com/gleam-lang/tree-sitter-gleam'
    ['glimmer']=' -url https://github.com/ember-tooling/tree-sitter-glimmer'
    ['glimmer-javascript']=' -url https://github.com/NullVoxPopuli/tree-sitter-glimmer-javascript'
    ['glimmer-typescript']=' -url https://github.com/NullVoxPopuli/tree-sitter-glimmer-typescript'
    ['glsl']=' -url https://github.com/theHamsta/tree-sitter-glsl'
    ['gn']=' -url https://github.com/amaanq/tree-sitter-gn'
    ['gnuplot']=' -url https://github.com/dpezto/tree-sitter-gnuplot'
    ['go']=' -url https://github.com/tree-sitter/tree-sitter-go'
    ['goctl']=' -url https://github.com/chaozwn/tree-sitter-goctl'
    ['godot-resource']=' -url https://github.com/PrestonKnopp/tree-sitter-godot-resource'
    ['gomod']=' -url https://github.com/camdencheek/tree-sitter-go-mod'
    ['gosum']=' -url https://github.com/amaanq/tree-sitter-go-sum'
    ['gotmpl']=' -url https://github.com/ngalaiko/tree-sitter-go-template'
    ['gowork']=' -url https://github.com/omertuc/tree-sitter-go-work'
    ['gpg']=' -url https://github.com/ObserverOfTime/tree-sitter-gpg-config'
    ['graphql']=' -url https://github.com/bkegley/tree-sitter-graphql'
    ['gren']=' -url https://github.com/MaeBrooks/tree-sitter-gren'
    ['groovy']=' -url https://github.com/murtaza64/tree-sitter-groovy'
    ['gstlaunch']=' -url https://github.com/theHamsta/tree-sitter-gstlaunch'
    ['hack']=' -url https://github.com/slackhq/tree-sitter-hack'
    ['hare']=' -url https://github.com/amaanq/tree-sitter-hare'
    ['haskell']=' -url https://github.com/tree-sitter/tree-sitter-haskell'
    ['haskell-persistent']=' -url https://github.com/MercuryTechnologies/tree-sitter-haskell-persistent'
    ['hcl']=' -url https://github.com/MichaHoffmann/tree-sitter-hcl'
    ['heex']=' -url https://github.com/connorlay/tree-sitter-heex'
    ['helm']=' -url https://github.com/ngalaiko/tree-sitter-go-template -src dialects/helm/src'
    ['hjson']=' -url https://github.com/winston0410/tree-sitter-hjson'
    ['hlsl']=' -url https://github.com/theHamsta/tree-sitter-hlsl'
    ['hlsplaylist']=' -url https://github.com/Freed-Wu/tree-sitter-hlsplaylist'
    ['hocon']=' -url https://github.com/antosha417/tree-sitter-hocon'
    ['hoon']=' -url https://github.com/urbit-pilled/tree-sitter-hoon'
    ['html']=' -url https://github.com/tree-sitter/tree-sitter-html'
    ['htmldjango']=' -url https://github.com/interdependence/tree-sitter-htmldjango'
    ['http']=' -url https://github.com/rest-nvim/tree-sitter-http'
    ['hurl']=' -url https://github.com/pfeiferj/tree-sitter-hurl'
    ['hyprlang']=' -url https://github.com/luckasRanarison/tree-sitter-hyprlang'
    ['idl']=' -url https://github.com/cathaysia/tree-sitter-idl'
    ['ini']=' -url https://github.com/justinmk/tree-sitter-ini'
    ['inko']=' -url https://github.com/inko-lang/tree-sitter-inko'
    ['ispc']=' -url https://github.com/fab4100/tree-sitter-ispc'
    ['janet-simple']=' -url https://github.com/sogaiu/tree-sitter-janet-simple'
    ['java']=' -url https://github.com/tree-sitter/tree-sitter-java'
    ['javascript']=' -url https://github.com/tree-sitter/tree-sitter-javascript'
    ['jq']=' -url https://github.com/flurie/tree-sitter-jq'
    ['jsdoc']=' -url https://github.com/tree-sitter/tree-sitter-jsdoc'
    ['json']=' -url https://github.com/tree-sitter/tree-sitter-json'
    ['json5']=' -url https://github.com/Joakker/tree-sitter-json5'
    ['jsonc']=' -url https://gitlab.com/WhyNotHugo/tree-sitter-jsonc.git'
    ['jsonnet']=' -url https://github.com/sourcegraph/tree-sitter-jsonnet'
    ['julia']=' -url https://github.com/tree-sitter/tree-sitter-julia'
    ['just']=' -url https://github.com/IndianBoy42/tree-sitter-just'
    ['kconfig']=' -url https://github.com/amaanq/tree-sitter-kconfig'
    ['kdl']=' -url https://github.com/amaanq/tree-sitter-kdl'
    ['kotlin']=' -url https://github.com/fwcd/tree-sitter-kotlin'
    ['koto']=' -url https://github.com/koto-lang/tree-sitter-koto'
    ['kusto']=' -url https://github.com/Willem-J-an/tree-sitter-kusto'
    ['lalrpop']=' -url https://github.com/traxys/tree-sitter-lalrpop'
    ['latex']=' -url https://github.com/latex-lsp/tree-sitter-latex'
    ['ledger']=' -url https://github.com/cbarrete/tree-sitter-ledger'
    ['leo']=' -url https://github.com/r001/tree-sitter-leo'
    ['linkerscript']=' -url https://github.com/amaanq/tree-sitter-linkerscript'
    ['liquid']=' -url https://github.com/hankthetank27/tree-sitter-liquid'
    ['liquidsoap']=' -url https://github.com/savonet/tree-sitter-liquidsoap'
    ['llvm']=' -url https://github.com/benwilliamgraham/tree-sitter-llvm'
    ['lua']=' -url https://github.com/MunifTanjim/tree-sitter-lua'
    ['luadoc']=' -url https://github.com/amaanq/tree-sitter-luadoc'
    ['luap']=' -url https://github.com/amaanq/tree-sitter-luap'
    ['luau']=' -url https://github.com/amaanq/tree-sitter-luau'
    ['m68k']=' -url https://github.com/grahambates/tree-sitter-m68k'
    ['make']=' -url https://github.com/alemuller/tree-sitter-make'
    ['markdown']=' -url https://github.com/tree-sitter-grammars/tree-sitter-markdown -rev split_parser -src tree-sitter-markdown/src'
    ['markdown-inline']=' -url https://github.com/tree-sitter-grammars/tree-sitter-markdown -rev split_parser -src tree-sitter-markdown-inline/src'
    ['matlab']=' -url https://github.com/acristoffers/tree-sitter-matlab'
    ['mediawiki']=' -url https://github.com/Ordoviz/tree-sitter-mediawiki'
    ['menhir']=' -url https://github.com/Kerl13/tree-sitter-menhir'
    ['mermaid']=' -url https://github.com/monaqa/tree-sitter-mermaid'
    ['meson']=' -url https://github.com/Decodetalkers/tree-sitter-meson'
    ['mlir']=' -url https://github.com/artagnon/tree-sitter-mlir'
    ['muttrc']=' -url https://github.com/neomutt/tree-sitter-muttrc'
    ['nasm']=' -url https://github.com/naclsn/tree-sitter-nasm'
    ['nginx']=' -url https://github.com/opa-oz/tree-sitter-nginx'
    ['nickel']=' -url https://github.com/nickel-lang/tree-sitter-nickel'
    ['nim']=' -url https://github.com/alaviss/tree-sitter-nim'
    ['nim_format-string']=' -url https://github.com/aMOPel/tree-sitter-nim-format-string'
    ['ninja']=' -url https://github.com/alemuller/tree-sitter-ninja'
    ['nix']=' -url https://github.com/cstrahan/tree-sitter-nix'
    ['norg']=' -url https://github.com/nvim-neorg/tree-sitter-norg'
    ['nqc']=' -url https://github.com/amaanq/tree-sitter-nqc'
    ['objc']=' -url https://github.com/amaanq/tree-sitter-objc'
    ['objdump']=' -url https://github.com/ColinKennedy/tree-sitter-objdump'
    ['ocaml']=' -url https://github.com/tree-sitter/tree-sitter-ocaml -src grammars/ocaml/src'
    ['ocaml-interface']=' -url https://github.com/tree-sitter/tree-sitter-ocaml -src grammars/interface/src'
    ['ocaml-type']=' -url https://github.com/tree-sitter/tree-sitter-ocaml -src grammars/type/src'
    ['ocamllex']=' -url https://github.com/atom-ocaml/tree-sitter-ocamllex'
    ['odin']=' -url https://github.com/amaanq/tree-sitter-odin'
    ['org']=' -url https://github.com/milisims/tree-sitter-org'
    ['pascal']=' -url https://github.com/Isopod/tree-sitter-pascal'
    ['passwd']=' -url https://github.com/ath3/tree-sitter-passwd'
    ['pem']=' -url https://github.com/ObserverOfTime/tree-sitter-pem'
    ['perl']=' -url https://github.com/tree-sitter-perl/tree-sitter-perl -rev release'
    ['php']=' -url https://github.com/tree-sitter/tree-sitter-php -src php/src'
    ['php-only']=' -url https://github.com/tree-sitter/tree-sitter-php -src php_only/src'
    ['phpdoc']=' -url https://github.com/claytonrcarter/tree-sitter-phpdoc'
    ['pioasm']=' -url https://github.com/leo60228/tree-sitter-pioasm'
    ['po']=' -url https://github.com/erasin/tree-sitter-po'
    ['pod']=' -url https://github.com/tree-sitter-perl/tree-sitter-pod -rev release'
    ['poe-filter']=' -url https://github.com/ObserverOfTime/tree-sitter-poe-filter'
    ['pony']=' -url https://github.com/amaanq/tree-sitter-pony'
    ['powershell']=' -url https://github.com/airbus-cert/tree-sitter-powershell'
    ['printf']=' -url https://github.com/ObserverOfTime/tree-sitter-printf'
    ['prisma']=' -url https://github.com/victorhqc/tree-sitter-prisma'
    ['problog']=' -url https://github.com/foxyseta/tree-sitter-prolog -src grammars/problog/src'
    ['prolog']=' -url https://github.com/foxyseta/tree-sitter-prolog -src grammars/prolog/src'
    ['promql']=' -url https://github.com/MichaHoffmann/tree-sitter-promql'
    ['properties']=' -url https://github.com/tree-sitter-grammars/tree-sitter-properties'
    ['proto']=' -url https://github.com/treywood/tree-sitter-proto'
    ['prql']=' -url https://github.com/PRQL/tree-sitter-prql'
    ['psv']=' -url https://github.com/amaanq/tree-sitter-csv -src psv/src'
    ['pug']=' -url https://github.com/zealot128/tree-sitter-pug'
    ['puppet']=' -url https://github.com/amaanq/tree-sitter-puppet'
    ['purescript']=' -url https://github.com/postsolar/tree-sitter-purescript'
    ['pymanifest']=' -url https://github.com/ObserverOfTime/tree-sitter-pymanifest'
    ['python']=' -url https://github.com/tree-sitter/tree-sitter-python'
    ['ql']=' -url https://github.com/tree-sitter/tree-sitter-ql'
    ['qmldir']=' -url https://github.com/Decodetalkers/tree-sitter-qmldir'
    ['qmljs']=' -url https://github.com/yuja/tree-sitter-qmljs'
    ['query']=' -url https://github.com/nvim-treesitter/tree-sitter-query'
    ['r']=' -url https://github.com/r-lib/tree-sitter-r'
    ['racket']=' -url https://github.com/6cdh/tree-sitter-racket'
    ['ralph']=' -url https://github.com/alephium/tree-sitter-ralph'
    ['rasi']=' -url https://github.com/Fymyte/tree-sitter-rasi'
    ['rbs']=' -url https://github.com/joker1007/tree-sitter-rbs'
    ['re2c']=' -url https://github.com/amaanq/tree-sitter-re2c'
    ['readline']=' -url https://github.com/ribru17/tree-sitter-readline'
    ['regex']=' -url https://github.com/tree-sitter/tree-sitter-regex'
    ['rego']=' -url https://github.com/FallenAngel97/tree-sitter-rego'
    ['requirements']=' -url https://github.com/ObserverOfTime/tree-sitter-requirements'
    ['rescript']=' -url https://github.com/rescript-lang/tree-sitter-rescript'
    ['rnoweb']=' -url https://github.com/bamonroe/tree-sitter-rnoweb'
    ['robot']=' -url https://github.com/Hubro/tree-sitter-robot'
    ['robots']=' -url https://github.com/opa-oz/tree-sitter-robots-txt'
    ['roc']=' -url https://github.com/faldor20/tree-sitter-roc'
    ['ron']=' -url https://github.com/amaanq/tree-sitter-ron'
    ['rst']=' -url https://github.com/stsewd/tree-sitter-rst'
    ['ruby']=' -url https://github.com/tree-sitter/tree-sitter-ruby'
    ['rust']=' -url https://github.com/tree-sitter/tree-sitter-rust'
    ['scala']=' -url https://github.com/tree-sitter/tree-sitter-scala'
    ['scfg']=' -url https://github.com/rockorager/tree-sitter-scfg'
    ['scheme']=' -url https://github.com/6cdh/tree-sitter-scheme'
    ['scss']=' -url https://github.com/serenadeai/tree-sitter-scss'
    ['sflog']=' -url https://github.com/aheber/tree-sitter-sfapex -src sflog/src'
    ['slang']=' -url https://github.com/theHamsta/tree-sitter-slang'
    ['slint']=' -url https://github.com/slint-ui/tree-sitter-slint'
    ['smali']=' -url https://github.com/tree-sitter-grammars/tree-sitter-smali'
    ['smithy']=' -url https://github.com/indoorvivants/tree-sitter-smithy'
    ['snakemake']=' -url https://github.com/osthomas/tree-sitter-snakemake'
    ['solidity']=' -url https://github.com/JoranHonig/tree-sitter-solidity'
    ['soql']=' -url https://github.com/aheber/tree-sitter-sfapex -src soql/src'
    ['sosl']=' -url https://github.com/aheber/tree-sitter-sfapex -src sosl/src'
    ['sourcepawn']=' -url https://github.com/nilshelmig/tree-sitter-sourcepawn'
    ['sparql']=' -url https://github.com/BonaBeavis/tree-sitter-sparql'
    ['sparql']=' -url https://github.com/GordianDziwis/tree-sitter-sparql'
    ['sql']=' -url https://github.com/derekstride/tree-sitter-sql -rev gh-pages'
    ['squirrel']=' -url https://github.com/amaanq/tree-sitter-squirrel'
    ['ssh-config']=' -url https://github.com/ObserverOfTime/tree-sitter-ssh-config'
    ['starlark']=' -url https://github.com/amaanq/tree-sitter-starlark'
    ['strace']=' -url https://github.com/sigmaSd/tree-sitter-strace'
    ['styled']=' -url https://github.com/mskelton/tree-sitter-styled'
    ['supercollider']=' -url https://github.com/madskjeldgaard/tree-sitter-supercollider'
    ['superhtml']=' -url https://github.com/kristoff-it/superhtml -src tree-sitter-superhtml/src'
    ['surface']=' -url https://github.com/connorlay/tree-sitter-surface'
    ['svelte']=' -url https://github.com/tree-sitter-grammars/tree-sitter-svelte'
    ['swift']=' -url https://github.com/alex-pinkus/tree-sitter-swift'
    ['sxhkdrc']=' -url https://github.com/RaafatTurki/tree-sitter-sxhkdrc'
    ['systemtap']=' -url https://github.com/ok-ryoko/tree-sitter-systemtap'
    ['t32']=' -url https://gitlab.com/xasc/tree-sitter-t32.git'
    ['tablegen']=' -url https://github.com/amaanq/tree-sitter-tablegen'
    ['tact']=' -url https://github.com/tact-lang/tree-sitter-tact'
    ['tcl']=' -url https://github.com/tree-sitter-grammars/tree-sitter-tcl'
    ['teal']=' -url https://github.com/euclidianAce/tree-sitter-teal'
    ['templ']=' -url https://github.com/vrischmann/tree-sitter-templ'
    ['terraform']=' -url https://github.com/MichaHoffmann/tree-sitter-hcl -src dialects/terraform/src'
    ['textproto']=' -url https://github.com/PorterAtGoogle/tree-sitter-textproto'
    ['thrift']=' -url https://github.com/duskmoon314/tree-sitter-thrift'
    ['tiger']=' -url https://github.com/ambroisie/tree-sitter-tiger'
    ['tlaplus']=' -url https://github.com/tlaplus-community/tree-sitter-tlaplus'
    ['tmux']=' -url https://github.com/Freed-Wu/tree-sitter-tmux'
    ['todotxt']=' -url https://github.com/arnarg/tree-sitter-todotxt'
    ['toml']=' -url https://github.com/tree-sitter-grammars/tree-sitter-toml'
    ['tsv']=' -url https://github.com/amaanq/tree-sitter-csv -src tsv/src'
    ['tsx']=' -url https://github.com/tree-sitter/tree-sitter-typescript -src tsx/src'
    ['turtle']=' -url https://github.com/GordianDziwis/tree-sitter-turtle'
    ['twig']=' -url https://github.com/gbprod/tree-sitter-twig'
    ['typescript']=' -url https://github.com/tree-sitter/tree-sitter-typescript -src typescript/src'
    ['typespec']=' -url https://github.com/happenslol/tree-sitter-typespec'
    ['typoscript']=' -url https://github.com/Teddytrombone/tree-sitter-typoscript'
    ['typst']=' -url https://github.com/uben0/tree-sitter-typst'
    ['udev']=' -url https://github.com/ObserverOfTime/tree-sitter-udev'
    ['ungrammar']=' -url https://github.com/Philipp-M/tree-sitter-ungrammar'
    ['unison']=' -url https://github.com/kylegoetz/tree-sitter-unison'
    ['usd']=' -url https://github.com/ColinKennedy/tree-sitter-usd'
    ['uxntal']=' -url https://github.com/amaanq/tree-sitter-uxntal'
    ['v']=' -url https://github.com/vlang/v-analyzer -src tree_sitter_v/src'
    ['vala']=' -url https://github.com/vala-lang/tree-sitter-vala'
    ['vento']=' -url https://github.com/ventojs/tree-sitter-vento'
    ['verilog']=' -url https://github.com/gmlarumbe/tree-sitter-systemverilog'
    ['vhdl']=' -url https://github.com/jpt13653903/tree-sitter-vhdl'
    ['vhs']=' -url https://github.com/charmbracelet/tree-sitter-vhs'
    ['vim']=' -url https://github.com/neovim/tree-sitter-vim'
    ['vimdoc']=' -url https://github.com/neovim/tree-sitter-vimdoc'
    ['vls']=' -url https://github.com/vlang/vls -src tree_sitter_v/src'
    ['vrl']=' -url https://github.com/belltoy/tree-sitter-vrl'
    ['vue']=' -url https://github.com/tree-sitter-grammars/tree-sitter-vue -rev main'
    ['wgsl']=' -url https://github.com/szebniok/tree-sitter-wgsl'
    ['wgsl-bevy']=' -url https://github.com/theHamsta/tree-sitter-wgsl-bevy'
    ['wing']=' -url https://github.com/winglang/tree-sitter-wing'
    ['wit']=' -url https://github.com/liamwh/tree-sitter-wit'
    ['xcompose']=' -url https://github.com/ObserverOfTime/tree-sitter-xcompose'
    ['xml']=' -url https://github.com/tree-sitter-grammars/tree-sitter-xml -src xml/src'
    ['xresources']=' -url https://github.com/ValdezFOmar/tree-sitter-xresources'
    ['yaml']=' -url https://github.com/tree-sitter-grammars/tree-sitter-yaml'
    ['yang']=' -url https://github.com/Hubro/tree-sitter-yang'
    ['yuck']=' -url https://github.com/Philipp-M/tree-sitter-yuck'
    ['zathurarc']=' -url https://github.com/Freed-Wu/tree-sitter-zathurarc'
    ['zig']=' -url https://github.com/tree-sitter-grammars/tree-sitter-zig'
    ['ziggy']=' -url https://github.com/kristoff-it/ziggy -src tree-sitter-ziggy/src'
    ['ziggy-schema']=' -url https://github.com/kristoff-it/ziggy -src tree-sitter-ziggy-schema/src'
)

project_root=$(cd "$(dirname "$BASH_SOURCE")/.."; pwd)
repos_dir="$project_root/repos"
grammars_dir="$project_root/bin"

soext=""
os=""
if [[ "$(uname)" == "Darwin"* ]]; then
    soext="dylib"
    os="macos"
elif [[ "$(uname)" == *"MINGW"* ]]; then
    soext="dll"
    os="windows"
else
    soext="so"
    os="linux"
fi

find_exec () {
    for prog in "$@"; do
        path=$(which "$prog" 2>/dev/null)
        if [ -n "$path" ]; then
            echo $path
            break
        fi
    done
}

cc=$(find_exec "cc" "gcc" "c99" "clang")
cc=${cc:-cc}
cpp=$(find_exec "c++" "g++" "clang++")
cpp=${cpp:-c++}

compile_grammar () {
    local lang=""
    local url=""
    local src=""
    local rev=""
    local target=""

    while [[ $# -gt 0 ]]; do
        case "$1" in
            -lang) lang=$2; shift ;;
            -url) url=$2; shift ;;
            -src) src=$2; shift ;;
            -rev) rev=$2; shift ;;
            -target) target=$2; shift ;;
            *)
                echo "Unknown option: $1"
                exit 1
                ;;
        esac
        shift
    done

    git clone $url --depth 1 --quiet "$repos_dir/$lang" ${rev:+-b $rev} || true
    cd "$repos_dir/$lang"

    src_dir="$repos_dir/$lang/${src:-src}"
    # generate parser if needed
    if [ ! -f "$src_dir/parser.c" ]; then
        echo "[INFO] Generate parser.c for $lang at $src_dir/parser.c"
        npm install --quiet || true
        npx tree-sitter generate || true
    fi

    # compile parser
    pushd "$src_dir"
    out_file="$grammars_dir/libtree-sitter-$lang.$soext"

    $cc -c -fPIC -g -flto=auto -O2 -I. parser.c ${target:+-target $target}
    if [ -f "scanner.cc" ]; then
        $cpp -c -fPIC -g -flto=auto -O2 -I. -std=c++20 -fno-exceptions scanner.cc ${target:+-target $target}
    fi

    if [ -f "scanner.c" ]; then
        $cc -c -fPIC -g -flto=auto -O2 -I. scanner.c ${target:+-target $target}
    fi

    ld=$([ -f "scanner.cc" ] && echo $cpp || echo $cc)
    $ld -s -shared -flto=auto -O2 -static-libstdc++ $([ $os = "macos" ] || echo -static-libgcc)  \
        ${target:+-target $target} *.o -o $out_file


    echo "[INFO] Finishing building `ls $out_file`"
}

create_bundle () {
    local version="$1"
    cd "$grammars_dir"
    echo $version > BUNDLE-VERSION
    out_file="$project_root/tree-sitter-grammars-$os-$version.tar.gz"
    echo "[INFO] Run: tar -zcvf $out_file BUNDLE-VERSION *.$soext"
    tar -zcvf $out_file BUNDLE-VERSION *.$soext
}
