#!/usr/bin/env bash
set -eo pipefail

declare -A grammars=(
    ['ada']=' -url https://github.com/briot/tree-sitter-ada'
    ['agda']=' -url https://github.com/AusCyberman/tree-sitter-agda'
    ['angular']=' -url https://github.com/dlvandenberg/tree-sitter-angular'
    ['apex']=' -url https://github.com/aheber/tree-sitter-sfapex -src apex/src'
    ['arduino']=' -url https://github.com/ObserverOfTime/tree-sitter-arduino'
    ['asm']=' -url https://github.com/RubixDev/tree-sitter-asm'
    ['astro']=' -url https://github.com/virchau13/tree-sitter-astro'
    ['authzed']=' -url https://github.com/mleonidas/tree-sitter-authzed'
    ['awk']=' -url https://github.com/Beaglefoot/tree-sitter-awk'
    ['bash']=' -url https://github.com/tree-sitter/tree-sitter-bash'
    ['bass']=' -url https://github.com/vito/tree-sitter-bass'
    ['beancount']=' -url https://github.com/polarmutex/tree-sitter-beancount'
    ['bibtex']=' -url https://github.com/latex-lsp/tree-sitter-bibtex'
    ['c']=' -url https://github.com/tree-sitter/tree-sitter-c'
    ['c-sharp']=' -url https://github.com/tree-sitter/tree-sitter-c-sharp'
    ['clojure']=' -url https://github.com/sogaiu/tree-sitter-clojure'
    ['cmake']=' -url https://github.com/uyha/tree-sitter-cmake'
    ['comment']=' -url https://github.com/stsewd/tree-sitter-comment'
    ['commonlisp']=' -url https://github.com/theHamsta/tree-sitter-commonlisp'
    ['cpp']=' -url https://github.com/tree-sitter/tree-sitter-cpp'
    ['css']=' -url https://github.com/tree-sitter/tree-sitter-css'
    ['csv']=' -url https://github.com/amaanq/tree-sitter-csv -src csv/src'
    ['cuda']=' -url https://github.com/theHamsta/tree-sitter-cuda'
    ['d']=' -url https://github.com/gdamore/tree-sitter-d'
    ['dart']=' -url https://github.com/UserNobody14/tree-sitter-dart'
    ['devicetree']=' -url https://github.com/joelspadin/tree-sitter-devicetree'
    ['diff']=' -url https://github.com/the-mikedavis/tree-sitter-diff'
    ['disassembly']=' -url https://github.com/ColinKennedy/tree-sitter-disassembly'
    ['dockerfile']=' -url https://github.com/camdencheek/tree-sitter-dockerfile'
    ['dot']=' -url https://github.com/rydesun/tree-sitter-dot'
    ['doxygen']=' -url https://github.com/amaanq/tree-sitter-doxygen'
    ['dtd']=' -url https://github.com/tree-sitter-grammars/tree-sitter-xml -src dtd/src'
    ['eex']=' -url https://github.com/connorlay/tree-sitter-eex'
    ['elisp']=' -url https://github.com/Wilfred/tree-sitter-elisp'
    ['elixir']=' -url https://github.com/elixir-lang/tree-sitter-elixir'
    ['elm']=' -url https://github.com/elm-tooling/tree-sitter-elm'
    ['elvish']=' -url https://github.com/ckafi/tree-sitter-elvish'
    ['erlang']=' -url https://github.com/AbstractMachinesLab/tree-sitter-erlang'
    ['fennel']=' -url https://github.com/travonted/tree-sitter-fennel'
    ['fidl']=' -url https://github.com/google/tree-sitter-fidl'
    ['fish']=' -url https://github.com/ram02z/tree-sitter-fish'
    ['fluent']=' -url https://github.com/tree-sitter/tree-sitter-fluent'
    ['fortran']=' -url https://github.com/stadelmanma/tree-sitter-fortran'
    ['fsharp']=' -url https://github.com/ionide/tree-sitter-fsharp.git'
    ['fusion']=' -url https://gitlab.com/jirgn/tree-sitter-fusion.git'
    ['git-config']=' -url https://github.com/the-mikedavis/tree-sitter-git-config'
    ['git-rebase']=' -url https://github.com/the-mikedavis/tree-sitter-git-rebase'
    ['gitattributes']=' -url https://github.com/ObserverOfTime/tree-sitter-gitattributes'
    ['gitcommit']=' -url https://github.com/gbprod/tree-sitter-gitcommit'
    ['gitignore']=' -url https://github.com/shunsambongi/tree-sitter-gitignore'
    ['gleam']=' -url https://github.com/J3RN/tree-sitter-gleam'
    ['glimmer']=' -url https://github.com/alexlafroscia/tree-sitter-glimmer'
    ['glsl']=' -url https://github.com/theHamsta/tree-sitter-glsl'
    ['gnuplot']=' -url https://github.com/dpezto/tree-sitter-gnuplot'
    ['go']=' -url https://github.com/tree-sitter/tree-sitter-go'
    ['go-mod']=' -url https://github.com/camdencheek/tree-sitter-go-mod'
    ['go-work']=' -url https://github.com/omertuc/tree-sitter-go-work'
    ['gomod']=' -url https://github.com/camdencheek/tree-sitter-go-mod'
    ['gotmpl']=' -url https://github.com/ngalaiko/tree-sitter-go-template'
    ['gowork']=' -url https://github.com/omertuc/tree-sitter-go-work'
    ['graphql']=' -url https://github.com/bkegley/tree-sitter-graphql'
    ['groovy']=' -url https://github.com/murtaza64/tree-sitter-groovy'
    ['haskell']=' -url https://github.com/tree-sitter/tree-sitter-haskell'
    ['hcl']=' -url https://github.com/MichaHoffmann/tree-sitter-hcl'
    ['heex']=' -url https://github.com/connorlay/tree-sitter-heex'
    ['helm']=' -url https://github.com/ngalaiko/tree-sitter-go-template -src dialects/helm/src'
    ['hjson']=' -url https://github.com/winston0410/tree-sitter-hjson'
    ['hlsl']=' -url https://github.com/theHamsta/tree-sitter-hlsl'
    ['hocon']=' -url https://github.com/antosha417/tree-sitter-hocon'
    ['html']=' -url https://github.com/tree-sitter/tree-sitter-html'
    ['http']=' -url https://github.com/rest-nvim/tree-sitter-http'
    ['java']=' -url https://github.com/tree-sitter/tree-sitter-java'
    ['javascript']=' -url https://github.com/tree-sitter/tree-sitter-javascript'
    ['jq']=' -url https://github.com/flurie/tree-sitter-jq'
    ['jsdoc']=' -url https://github.com/tree-sitter/tree-sitter-jsdoc'
    ['json']=' -url https://github.com/tree-sitter/tree-sitter-json'
    ['json5']=' -url https://github.com/Joakker/tree-sitter-json5'
    ['jsonnet']=' -url https://github.com/sourcegraph/tree-sitter-jsonnet'
    ['julia']=' -url https://github.com/tree-sitter/tree-sitter-julia'
    ['kotlin']=' -url https://github.com/fwcd/tree-sitter-kotlin'
    ['kusto']=' -url https://github.com/Willem-J-an/tree-sitter-kusto'
    ['lalrpop']=' -url https://github.com/traxys/tree-sitter-lalrpop'
    ['latex']=' -url https://github.com/latex-lsp/tree-sitter-latex '
    ['ledger']=' -url https://github.com/cbarrete/tree-sitter-ledger'
    ['llvm']=' -url https://github.com/benwilliamgraham/tree-sitter-llvm'
    ['lua']=' -url https://github.com/MunifTanjim/tree-sitter-lua'
    ['m68k']=' -url https://github.com/grahambates/tree-sitter-m68k'
    ['make']=' -url https://github.com/alemuller/tree-sitter-make'
    ['markdown']=' -url https://github.com/MDeiml/tree-sitter-markdown -src tree-sitter-markdown/src'
    ['markdown-inline']=' -url https://github.com/MDeiml/tree-sitter-markdown -src tree-sitter-markdown-inline/src'
    ['matlab']=' -url https://github.com/acristoffers/tree-sitter-matlab'
    ['mediawiki']=' -url https://github.com/Ordoviz/tree-sitter-mediawiki'
    ['menhir']=' -url https://github.com/Kerl13/tree-sitter-menhir'
    ['mermaid']=' -url https://github.com/monaqa/tree-sitter-mermaid'
    ['meson']=' -url https://github.com/Decodetalkers/tree-sitter-meson'
    ['nasm']=' -url https://github.com/naclsn/tree-sitter-nasm'
    ['nim']=' -url https://github.com/alaviss/tree-sitter-nim'
    ['ninja']=' -url https://github.com/alemuller/tree-sitter-ninja'
    ['nix']=' -url https://github.com/cstrahan/tree-sitter-nix'
    ['norg']=' -url https://github.com/nvim-neorg/tree-sitter-norg'
    ['objc']=' -url https://github.com/amaanq/tree-sitter-objc'
    ['objdump']=' -url https://github.com/ColinKennedy/tree-sitter-objdump'
    ['ocaml']=' -url https://github.com/tree-sitter/tree-sitter-ocaml -src grammars/ocaml/src'
    ['ocaml-interface']=' -url https://github.com/tree-sitter/tree-sitter-ocaml -src grammars/interface/src'
    ['ocaml-type']=' -url https://github.com/tree-sitter/tree-sitter-ocaml -src grammars/type/src'
    ['ocamllex']=' -url https://github.com/atom-ocaml/tree-sitter-ocamllex'
    ['pascal']=' -url https://github.com/Isopod/tree-sitter-pascal'
    ['perl']=' -url https://github.com/tree-sitter-perl/tree-sitter-perl -rev release'
    ['pgn']=' -url https://github.com/rolandwalker/tree-sitter-pgn.git'
    ['php']=' -url https://github.com/tree-sitter/tree-sitter-php -src php/src'
    ['pioasm']=' -url https://github.com/leo60228/tree-sitter-pioasm'
    ['powershell']=' -url https://github.com/airbus-cert/tree-sitter-powershell'
    ['prisma']=' -url https://github.com/victorhqc/tree-sitter-prisma'
    ['proto']=' -url https://github.com/treywood/tree-sitter-proto'
    ['psv']=' -url https://github.com/amaanq/tree-sitter-csv -src psv/src'
    ['python']=' -url https://github.com/tree-sitter/tree-sitter-python'
    ['ql']=' -url https://github.com/tree-sitter/tree-sitter-ql'
    ['qmljs']=' -url https://github.com/yuja/tree-sitter-qmljs'
    ['query']=' -url https://github.com/nvim-treesitter/tree-sitter-query'
    ['r']=' -url https://github.com/r-lib/tree-sitter-r.git'
    ['racket']=' -url https://github.com/6cdh/tree-sitter-racket'
    ['rasi']=' -url https://github.com/Fymyte/tree-sitter-rasi'
    ['regex']=' -url https://github.com/tree-sitter/tree-sitter-regex'
    ['rego']=' -url https://github.com/FallenAngel97/tree-sitter-rego'
    ['rnoweb']=' -url https://github.com/bamonroe/tree-sitter-rnoweb'
    ['rst']=' -url https://github.com/stsewd/tree-sitter-rst'
    ['ruby']=' -url https://github.com/tree-sitter/tree-sitter-ruby'
    ['rust']=' -url https://github.com/tree-sitter/tree-sitter-rust'
    ['scala']=' -url https://github.com/tree-sitter/tree-sitter-scala'
    ['scheme']=' -url https://github.com/6cdh/tree-sitter-scheme.git'
    ['scss']=' -url https://github.com/serenadeai/tree-sitter-scss'
    ['solidity']=' -url https://github.com/JoranHonig/tree-sitter-solidity'
    ['sparql']=' -url https://github.com/BonaBeavis/tree-sitter-sparql'
    ['sql']=' -url https://github.com/derekstride/tree-sitter-sql -rev gh-pages'
    ['supercollider']=' -url https://github.com/madskjeldgaard/tree-sitter-supercollider'
    ['surface']=' -url https://github.com/connorlay/tree-sitter-surface'
    ['svelte']=' -url https://github.com/Himujjal/tree-sitter-svelte'
    ['swift']=' -url https://github.com/alex-pinkus/tree-sitter-swift '
    ['sxhkdrc']=' -url https://github.com/RaafatTurki/tree-sitter-sxhkdrc'
    ['teal']=' -url https://github.com/euclidianAce/tree-sitter-teal '
    ['tiger']=' -url https://github.com/ambroisie/tree-sitter-tiger'
    ['tlaplus']=' -url https://github.com/tlaplus-community/tree-sitter-tlaplus'
    ['tmux']=' -url https://github.com/Freed-Wu/tree-sitter-tmux'
    ['toml']=' -url https://github.com/ikatyang/tree-sitter-toml'
    ['tsv']=' -url https://github.com/amaanq/tree-sitter-csv -src tsv/src'
    ['tsx']=' -url https://github.com/tree-sitter/tree-sitter-typescript -src tsx/src'
    ['turtle']=' -url https://github.com/BonaBeavis/tree-sitter-turtle'
    ['twig']=' -url https://github.com/gbprod/tree-sitter-twig'
    ['typescript']=' -url https://github.com/tree-sitter/tree-sitter-typescript -src typescript/src'
    ['vala']=' -url https://github.com/vala-lang/tree-sitter-vala'
    ['verilog']=' -url https://github.com/tree-sitter/tree-sitter-verilog.git'
    ['vhs']=' -url https://github.com/charmbracelet/tree-sitter-vhs'
    ['vim']=' -url https://github.com/neovim/tree-sitter-vim'
    ['vimdoc']=' -url https://github.com/neovim/tree-sitter-vimdoc'
    ['vls']=' -url https://github.com/vlang/vls -src tree_sitter_v/src'
    ['vue']=' -url https://github.com/ikatyang/tree-sitter-vue'
    ['wgsl']=' -url https://github.com/szebniok/tree-sitter-wgsl'
    ['xml']=' -url https://github.com/tree-sitter-grammars/tree-sitter-xml -src xml/src'
    ['yaml']=' -url https://github.com/ikatyang/tree-sitter-yaml'
    ['yang']=' -url https://github.com/Hubro/tree-sitter-yang'
    ['zig']=' -url https://github.com/maxxnino/tree-sitter-zig'
)

project_root=$(cd "$(dirname "$BASH_SOURCE")/.."; pwd)
repos_dir="$project_root/repos"
grammars_dir="$project_root/bin"

soext=""
os=""
if [[ "$(uname)" == "Darwin"* ]]; then
    soext="dylib"
    os="macos"
elif [[ "$(uname)" == *"MINGW"* ]]; then
    soext="dll"
    os="windows"
else
    soext="so"
    os="linux"
fi

find_exec () {
    for prog in "$@"; do
        path=$(which "$prog" 2>/dev/null)
        if [ -n "$path" ]; then
            echo $path
            break
        fi
    done
}

cc=$(find_exec "cc" "gcc" "c99" "clang")
cc=${cc:-cc}
cpp=$(find_exec "c++" "g++" "clang++")
cpp=${cpp:-c++}

compile_grammar () {
    local lang=""
    local url=""
    local src=""
    local rev=""
    local target=""

    while [[ $# -gt 0 ]]; do
        case "$1" in
            -lang) lang=$2; shift ;;
            -url) url=$2; shift ;;
            -src) src=$2; shift ;;
            -rev) rev=$2; shift ;;
            -target) target=$2; shift ;;
            *)
                echo "Unknown option: $1"
                exit 1
                ;;
        esac
        shift
    done

    git clone $url --depth 1 --quiet "$repos_dir/$lang" ${rev:+-b $rev} || true
    cd "$repos_dir/$lang"

    src_dir="$repos_dir/$lang/${src:-src}"
    # generate parser if needed
    if [ ! -f "$src_dir/parser.c" ]; then
        echo "[INFO] Generate parser.c for $lang at $src_dir/parser.c"
        npm install --quiet || true
        npx tree-sitter generate || true
    fi

    # compile parser
    pushd "$src_dir"
    out_file="$grammars_dir/libtree-sitter-$lang.$soext"

    $cc -c -fPIC -g -flto=auto -O2 -I. parser.c ${target:+-target $target}
    if [ -f "scanner.cc" ]; then
        $cpp -c -fPIC -g -flto=auto -O2 -I. -std=c++20 -fno-exceptions scanner.cc ${target:+-target $target}
    fi

    if [ -f "scanner.c" ]; then
        $cc -c -fPIC -g -flto=auto -O2 -I. scanner.c ${target:+-target $target}
    fi

    ld=$([ -f "scanner.cc" ] && echo $cpp || echo $cc)
    $ld -shared -flto=auto -O2 -static-libstdc++ $([ $os = "macos" ] || echo -static-libgcc)  \
        ${target:+-target $target} *.o -o $out_file


    echo "[INFO] Finishing building `ls $out_file`"
}

create_bundle () {
    local version="$1"
    cd "$grammars_dir"
    echo $version > BUNDLE-VERSION
    out_file="$project_root/tree-sitter-grammars-$os-$version.tar.gz"
    echo "[INFO] Run: tar -zcvf $out_file BUNDLE-VERSION *.$soext"
    tar -zcvf $out_file BUNDLE-VERSION *.$soext
}
