#!/usr/bin/env bash
#
# Usage:
#    compile <lang-name>
#    compile all
#    compile changed [since=origin/master]
#
# Examples:
#    compile rust
#    compile cpp
#
#    compile changed 0.10.7

set -euo pipefail

here=$(cd "$(dirname "$BASH_SOURCE")"; pwd)
PROJECT_ROOT=$(cd "$here/.."; pwd)

LANG=$1

# Parse named parameters.
POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        (-target)
            target="'$2"
            shift
            shift
            ;;
        (-version)
            version="\"$2\""
            shift
            shift
            ;;
        (*)
            POSITIONAL+=("$1")
            shift
            ;;
    esac
done
target=${target:-nil}
if [ "$target" == "'" ]; then
    target=nil
fi
if [ "$version" == "\"\"" ]; then
  version=nil
fi

case $LANG in
    (all)
        code="(treesit-langs-create-bundle nil $target $version)"
        ;;
    (changed)
        code="(treesit-langs-compile-changed-or-all \"${POSITIONAL[1]:-origin/master}\" $target)"
        ;;
    (*)
        code="(treesit-langs-compile '$LANG nil $target)"
esac

(
    cd "$PROJECT_ROOT"
    emacs -Q --batch \
          --directory . \
          --load treesit-langs-build \
          --eval "$code"
)
